### ISSUE TITLE
[Task] feature/10/Myfridge Add Contents

### ISSUE THREAD

**Issue by yrkimyy** [codestates/waf-client#10]
## Task Card

**Part** : 클라이언트

### Job Description
> Myfridge Add Contents

### TODO
1. [x] 냉장고 위에 username님의 냉장고 작성
2. [x] 냉장고 그리드 작성
3. [x] 냉장고 안에 컨텐츠 삽입
4. [x] 로그아웃 버튼 생성
