### ISSUE TITLE
[Task] feature/14/Login C modify after connecting to server

### ISSUE THREAD

**Issue by yrkimyy** [codestates/waf-client#14]
## Task Card

**Part** : 클라이언트

### Job Description
> 로그인 컴포넌트 서버에 접속하고 수정하기

### TODO
1. [x] 데이터 받아오는지 확인
2. [x] 데이터 받고, 로그인 되는지 확인
3. [x] 로그인 하고 화면전환
4. [x] 가져와야할 데이터 다시 확인

응### Labels
Estimated time: E: 1h
Urgency: High, UltraHigh, ExtremelyHigh
