### ISSUE TITLE
[Task] feature/41/Recipe_C_and_player_C write

### ISSUE THREAD

**Issue by yrkimyy** [codestates/waf-client#41]
## Task Card

**Part** : 클라이언트
### Job Description
> 레시피 컴포넌트 만들기

### TODO
1. [x] 컴포넌트 뼈대잡기
2. [x] 상하위 컴포넌트 연결하기
3. [x] youtube API로 불러오기
4. [x] 서버랑 연결해서 데이터 받아오는지 확인하기
5. [x] 클릭 시, player C로 연결하기 
6. [x] player C에서 잘 받아오는지 확인하기

### Labels
Estimated time: E: 1h
Urgency: High, UltraHigh, ExtremelyHigh
