### ISSUE TITLE
[Task] Recipe_C_wirte

### ISSUE THREAD

**Issue by dawa93** [codestates/waf-client#45]
## Task Card

**Part** : 클라이언트

### Job Description
> 재료를 클릭했을때, 그 재료에 맞는 요리 레시피를 영상으로 볼 수 있는 페이지를 구현하기

### TODO
1. [x] 사용자 정보를 화면에 구현하고, 뒤로 가기 버튼 만들기
2. [x] 비디오를 볼 수 있는 비디오 플레이어 만들기
3. [x] 다른 레시피를 볼 수 있는 레시피 리스트업 구현하기

### Labels
Estimated time: E: 3h
Urgency: High, UltraHigh, ExtremelyHigh
