### ISSUE TITLE
[Task] Myfridge(Demo) C write

### ISSUE THREAD

**Issue by yrkimyy** [codestates/waf-client#5]
## Task Card

**Part** : 클라이언트

### Job Description
> Myfridge(demo) 컴포넌트 작성

### TODO
1. [ ] 회원가입 모달
2. [ ] 네 응답 버튼 => 사인업으로 리다이렉트
3. [ ] 아니오 응답버튼 => 홈으로 리다이렉트
----------------------------------------------
4. [ ] 냉장고 이미지 삽입
5. [ ] 냉장고 그리드 작업
6. [ ] username님의 냉장고 태그 삽입
7. [ ] 로그아웃버튼
