### ISSUE TITLE
[Task] feature/9/Myfridge C write sidebar

### ISSUE THREAD

**Issue by yrkimyy** [codestates/waf-client#9]
## Task Card

**Part** : 클라이언트 

### Job Description
>Myfridge C write sidebar

### TODO
1. [x] sidebar 생성
2. [x] sidebar (-)버튼 생성
3. [x] sidebar 소비기한 설정
4. [x] sidebar 냉장/냉동 변경 가능 설정
5. [x] sidebar 데이터 서버에서 받아오기
